color0 #37271b
color1 #b97747
color2 #e49d67
color3 #d6cd5c
color4 #a1d35f
color5 #ecb993
color6 #e9e396
color7 #f3f2f2
color8 #716861
color9 #b97747
color10 #e49d67
color11 #d6cd5c
color12 #a1d35f
color13 #ecb993
color14 #e9e396
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291d14
background            #291d14
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #37271b
active_border_color   #e49d67
inactive_border_color #37271b
url_color             #e49d67

active_tab_foreground   #251e18
active_tab_background   #e49d67
inactive_tab_foreground #b6b2af
inactive_tab_background #37271b
cursor_trail_color      #b6b2af
