gui:
  theme:
    activeBorderColor:
      - "#e49d67"
      - bold
    inactiveBorderColor:
      - "#d6cd5c"
    searchingActiveBorderColor:
      - "#a1d35f"
      - bold
    optionsTextColor:
      - "#b6b2af"
    selectedLineBgColor:
      - "#b6b2af"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b6b2af"
    cherryPickedCommitBgColor:
      - "#a1d35f"
    markedBaseCommitFgColor:
      - "#a1d35f"
    markedBaseCommitBgColor:
      - "#9a5a2a"
    unstagedChangesColor:
      - "#9a5a2a"
    defaultFgColor:
      - "#f3f2f2"
